// Generated by CoffeeScript 1.9.1
(function() {
  var Controller, Game;

  Game = require('./game');

  Controller = (function() {
    Controller.games;

    Controller.sio;

    function Controller(sio) {
      this.sio = sio;
      this.games = [];
    }

    Controller.prototype.createGame = function(code) {
      var game;
      game = new Game(this.sio, code);
      this.games.push(game);
      return game;
    };

    Controller.prototype.findByCode = function(code) {
      return null;
    };

    return Controller;

  })();

  module.exports = Controller;

}).call(this);
